### ISSUE TITLE
[BUG] SSH key doesn't work

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#173]
**Describe the bug**
My ssh key doesn't work with ercole

**Expected behavior**
It should use it without problem

**To Reproduce**
* Generate ssh key ` ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
* Use that key for ercole

**Screenshots, logs, stdout, stderr, asciinema**
```
panic: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2

goroutine 1 [running]:
github.com/amreo/ercole-services/api-service/auth.(*BasicAuthenticationProvider).Init(0xc000163ef0)
        /home/cirelli/Projects/open-mind/ercole-services/api-service/auth/simple_auth.go:60 +0x164
github.com/amreo/ercole-services/cmd.serveAPIService(0xc000229a00, 0x16, 0xc00023b440, 0x7, 0x10100012b67, 0xc00023b44c, 0x4, 0xc00023b450, 0x8, 0xc00023b460, ...)
        /home/cirelli/Projects/open-mind/ercole-services/cmd/serve.go:257 +0x2aa
github.com/amreo/ercole-services/cmd.serve(0x1010101)
        /home/cirelli/Projects/open-mind/ercole-services/cmd/serve.go:118 +0x183
github.com/amreo/ercole-services/cmd.glob..func28(0x163ea40, 0xc0002258a0, 0x0, 0x2)
        /home/cirelli/Projects/open-mind/ercole-services/cmd/serve.go:63 +0x82
github.com/spf13/cobra.(*Command).execute(0x163ea40, 0xc000225860, 0x2, 0x2, 0x163ea40, 0xc000225860)
        /home/cirelli/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x163e500, 0x44d2ba, 0x164bea0, 0xc000000180)
        /home/cirelli/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/cirelli/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/amreo/ercole-services/cmd.Execute()
        /home/cirelli/Projects/open-mind/ercole-services/cmd/root.go:46 +0x31
main.main()
        /home/cirelli/Projects/open-mind/ercole-services/main.go:21 +0x20
```

**Desktop (please complete the following information):**
 - OS: Manjaro
 - ercole version: 48c1206463f5fca8ad89d52eedb7581e7a593a4b
- ssh -V `OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019`

**Comment by anbrenna** [comment]
No longer required
